apiVersion: v1
kind: Service
metadata:
  name: ext-auth
  namespace: backend
  labels:
    app: ext-auth-service
spec:
  selector:
    app: ext-auth-service
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
  type: ClusterIP
